import { z } from "zod"
 
export const PersonalInFoSchema = z.object({
  fullName: z.string().min(2, "Name must be at least 2 characters").max(400, "Name must be less than 400 characters"),
  gender: z.string(),
  dob: z.date(),
  phoneNumber: z.string(),
  address: z.string(),
  email: z.string().email().optional(),
  emergency_contact_fullName: z.string().optional(),
  emergency_contact_phoneNumber: z.string().optional(),
  past_medical_conditions: z.string().optional(),
  current_medications: z.string().optional(),
  allergies: z.string().optional(),
  family_medical_history: z.string().optional(),
  immunization_records: z.string().optional(),
  primary_complaint: z.string().optional(),
  duration_of_symptoms: z.string(),
  nature_of_symptoms: z.string(),
  previous_consultations: z.string().optional(),
  diet_and_nutrition: z.string(),
  physical_activity: z.string().optional(),
  sleep_patterns: z.string(),
  substance_use: z.string().optional(),
  occupation_and_work_environment: z.string().optional(),
  living_situation: z.string().optional(),
  social_support: z.string().optional(),
  travel_history: z.string().optional(),
  insurance_provider_details: z.string().optional(),
  financial_concerns: z.string().optional(),
})
